# Generated by Django 2.1 on 2018-11-29 12:15

from django.db import migrations, models
import myaccount.models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0003_auto_20181120_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default.jpg', upload_to=myaccount.models.user_directory_path, verbose_name='头像'),
        ),
    ]
